# Generated by Django 5.1.15 on 2026-07-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_installation_id", models.BigIntegerField(unique=True)),
                ("account_login", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("User", "User"), ("Organization", "Organization")],
                        default="User",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Installation",
                "verbose_name_plural": "Installations",
                "db_table": "installation",
                "indexes": [
                    models.Index(
                        fields=["github_installation_id"], name="installatio_github__61e002_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_repo_id", models.BigIntegerField()),
                ("full_name", models.CharField(max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Repo-specific configuration. Keys: enabled_categories (list), private_repo_opt_in (bool), max_comments (int), custom_instructions (str)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repos",
                        to="sentinel_review.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
                "db_table": "repo",
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_pr_number", models.IntegerField()),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("author_login", models.CharField(blank=True, default="", max_length=255)),
                ("head_sha", models.CharField(blank=True, default="", max_length=40)),
                ("base_sha", models.CharField(blank=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed"), ("merged", "Merged")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="sentinel_review.repo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pull Request",
                "verbose_name_plural": "Pull Requests",
                "db_table": "pull_request",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_review_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("synchronize", "Synchronize"),
                            ("requested", "Requested"),
                        ],
                        default="opened",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        blank=True, help_text="LLM processing time in ms", null=True
                    ),
                ),
                (
                    "token_cost",
                    models.IntegerField(
                        blank=True, help_text="Total tokens used across all LLM calls", null=True
                    ),
                ),
                ("findings_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="sentinel_review.pullrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "review",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("github_comment_id", models.BigIntegerField(blank=True, null=True)),
                ("file_path", models.CharField(max_length=500)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("style", "Style"),
                            ("security", "Security"),
                            ("suggestion", "Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("blocking", "Blocking"), ("warning", "Warning"), ("nit", "Nit")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("suggested_fix", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="sentinel_review.review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        choices=[("thumbs_up", "👍 Thumbs Up"), ("thumbs_down", "👎 Thumbs Down")],
                        max_length=20,
                    ),
                ),
                ("reactor_login", models.CharField(blank=True, default="", max_length=255)),
                ("github_reaction_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="sentinel_review.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "db_table": "feedback",
                "indexes": [
                    models.Index(fields=["comment"], name="feedback_comment_751412_idx"),
                    models.Index(fields=["reaction"], name="feedback_reactio_eadf03_idx"),
                    models.Index(
                        fields=["comment", "reaction"], name="feedback_comment_8cc887_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comment", "reactor_login", "reaction"),
                        name="uq_feedback_comment_reactor_reaction",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="repo",
            index=models.Index(fields=["installation"], name="repo_install_c846af_idx"),
        ),
        migrations.AddIndex(
            model_name="repo",
            index=models.Index(fields=["full_name"], name="repo_full_na_567405_idx"),
        ),
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.UniqueConstraint(
                fields=("installation", "github_repo_id"), name="uq_repo_installation_github_id"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["repo"], name="pull_reques_repo_id_a19882_idx"),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["repo", "status"], name="pull_reques_repo_id_fd3e3d_idx"),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("repo", "github_pr_number"), name="uq_pull_request_repo_number"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["pull_request"], name="review_pull_re_ca5eca_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["status"], name="review_status_15ed7d_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["review"], name="comment_review__3f8b04_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["category"], name="comment_categor_66a142_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["severity"], name="comment_severit_447ced_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["review", "category"], name="comment_review__e7d2ab_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["review", "severity"], name="comment_review__ff909c_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["file_path", "line_number"], name="comment_file_pa_01e06a_idx"
            ),
        ),
    ]
