# Generated by Django 5.1.15 on 2026-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='estimated_cost_usd',
            field=models.FloatField(blank=True, help_text='Estimated USD cost based on token count and model pricing', null=True),
        ),
    ]
